DROP SCHEMA IF EXISTS pantrycat CASCADE;
CREATE SCHEMA pantrycat;
SET SCHEMA 'pantrycat';

DROP TABLE IF EXISTS RECIPES CASCADE;
CREATE TABLE RECIPES (
    recipeID        SERIAL PRIMARY KEY,
    name            VARCHAR(64),
    source          VARCHAR(128)
);

DROP TABLE IF EXISTS INGREDIENTS CASCADE;
CREATE TABLE INGREDIENTS (
    name            VARCHAR(64),
    CONSTRAINT INGREDIENTS_PK PRIMARY KEY(name)
);


DROP TABLE IF EXISTS USES CASCADE;
CREATE TABLE USES (
    recipe          INTEGER,
    ingredient      VARCHAR(64),
    CONSTRAINT USES_PK PRIMARY KEY(recipe, ingredient),
    CONSTRAINT USES_FK_RECIPE FOREIGN KEY(recipe) REFERENCES RECIPES(recipeID)
        ON UPDATE CASCADE ON DELETE CASCADE,
    CONSTRAINT USES_FK_INGREDIENT FOREIGN KEY(ingredient) REFERENCES INGREDIENTS(name)
        ON UPDATE CASCADE ON DELETE CASCADE,
    amount          VARCHAR(32),
    unit            VARCHAR(32),
    notes           VARCHAR(164)
);